2d IBPD w/ failure

diff --git a/examples/IBPD/explicit/ex2/Makefile.in b/examples/IBPD/explicit/ex2/Makefile.in
--- a/examples/IBPD/explicit/ex2/Makefile.in
+++ b/examples/IBPD/explicit/ex2/Makefile.in
@@ -87,8 +87,9 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
-EXTRA_PROGRAMS = $(am__EXEEXT_1)
-@SAMRAI3D_ENABLED_TRUE@am__append_1 = main3d failed_sheet3d_generator
+EXTRA_PROGRAMS = $(am__EXEEXT_1) $(am__EXEEXT_2)
+@SAMRAI2D_ENABLED_TRUE@am__append_1 = main2d failed_sheet2d_generator
+@SAMRAI3D_ENABLED_TRUE@am__append_2 = main3d failed_sheet3d_generator
 subdir = examples/IBPD/explicit/ex2
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/add_rpath.m4 \
@@ -120,21 +121,38 @@ mkinstalldirs = $(install_sh) -d
 CONFIG_HEADER = $(top_builddir)/config/IBAMR_config.h.tmp
 CONFIG_CLEAN_FILES =
 CONFIG_CLEAN_VPATH_FILES =
-@SAMRAI3D_ENABLED_TRUE@am__EXEEXT_1 = main3d$(EXEEXT) \
+@SAMRAI2D_ENABLED_TRUE@am__EXEEXT_1 = main2d$(EXEEXT) \
+@SAMRAI2D_ENABLED_TRUE@	failed_sheet2d_generator$(EXEEXT)
+@SAMRAI3D_ENABLED_TRUE@am__EXEEXT_2 = main3d$(EXEEXT) \
 @SAMRAI3D_ENABLED_TRUE@	failed_sheet3d_generator$(EXEEXT)
+am_failed_sheet2d_generator_OBJECTS =  \
+	failed_sheet2d_generator-generate_failed_sheet2d.$(OBJEXT)
+failed_sheet2d_generator_OBJECTS =  \
+	$(am_failed_sheet2d_generator_OBJECTS)
+failed_sheet2d_generator_DEPENDENCIES = $(IBAMR2d_LIBS) $(IBAMR_LIBS)
+AM_V_lt = $(am__v_lt_@AM_V@)
+am__v_lt_ = $(am__v_lt_@AM_DEFAULT_V@)
+am__v_lt_0 = --silent
+am__v_lt_1 = 
+failed_sheet2d_generator_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
+	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
+	$(failed_sheet2d_generator_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
+	$(LDFLAGS) -o $@
 am_failed_sheet3d_generator_OBJECTS =  \
 	failed_sheet3d_generator-generate_failed_sheet3d.$(OBJEXT)
 failed_sheet3d_generator_OBJECTS =  \
 	$(am_failed_sheet3d_generator_OBJECTS)
 failed_sheet3d_generator_DEPENDENCIES = $(IBAMR3d_LIBS) $(IBAMR_LIBS)
-AM_V_lt = $(am__v_lt_@AM_V@)
-am__v_lt_ = $(am__v_lt_@AM_DEFAULT_V@)
-am__v_lt_0 = --silent
-am__v_lt_1 = 
 failed_sheet3d_generator_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
 	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
 	$(failed_sheet3d_generator_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
 	$(LDFLAGS) -o $@
+am_main2d_OBJECTS = main2d-main.$(OBJEXT)
+main2d_OBJECTS = $(am_main2d_OBJECTS)
+main2d_DEPENDENCIES = $(IBAMR2d_LIBS) $(IBAMR_LIBS)
+main2d_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
+	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(main2d_CXXFLAGS) \
+	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
 am_main3d_OBJECTS = main3d-main.$(OBJEXT)
 main3d_OBJECTS = $(am_main3d_OBJECTS)
 main3d_DEPENDENCIES = $(IBAMR3d_LIBS) $(IBAMR_LIBS)
@@ -156,8 +174,9 @@ am__v_at_1 =
 DEFAULT_INCLUDES = -I.@am__isrc@ -I$(top_builddir)/config
 depcomp = $(SHELL) $(top_srcdir)/config/depcomp
 am__maybe_remake_depfiles = depfiles
-am__depfiles_remade = ./$(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Po \
-	./$(DEPDIR)/main3d-main.Po
+am__depfiles_remade = ./$(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Po \
+	./$(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Po \
+	./$(DEPDIR)/main2d-main.Po ./$(DEPDIR)/main3d-main.Po
 am__mv = mv -f
 CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
 	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
@@ -177,7 +196,9 @@ AM_V_CXXLD = $(am__v_CXXLD_@AM_V@)
 am__v_CXXLD_ = $(am__v_CXXLD_@AM_DEFAULT_V@)
 am__v_CXXLD_0 = @echo "  CXXLD   " $@;
 am__v_CXXLD_1 = 
-DIST_SOURCES = $(failed_sheet3d_generator_SOURCES) $(main3d_SOURCES)
+DIST_SOURCES = $(failed_sheet2d_generator_SOURCES) \
+	$(failed_sheet3d_generator_SOURCES) $(main2d_SOURCES) \
+	$(main3d_SOURCES)
 am__can_run_installinfo = \
   case $$AM_UPDATE_INFO_DIR in \
     n|no|NO) false;; \
@@ -469,11 +490,18 @@ IBAMR2d_LIBS = ${top_builddir}/lib/libIBAMR2d.a ${top_builddir}/ibtk/lib/libIBTK
 IBAMR3d_LIBS = ${top_builddir}/lib/libIBAMR3d.a ${top_builddir}/ibtk/lib/libIBTK3d.a
 pkg_includedir = $(includedir)/@PACKAGE@
 SUFFIXES = .f.m4
-SOURCES = main.cpp generate_failed_sheet3d.cpp
-EXTRA_DIST = input3d.failure generate_failed_sheet3d.cpp
+SOURCES = main.cpp generate_failed_sheet2d.cpp generate_failed_sheet3d.cpp
+EXTRA_DIST = input2d.failure input3d.failure \
+	generate_failed_sheet2d.cpp generate_failed_sheet3d.cpp
+main2d_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=2
+main2d_LDADD = $(IBAMR_LDFLAGS) $(IBAMR2d_LIBS) $(IBAMR_LIBS)
+main2d_SOURCES = main.cpp
 main3d_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=3
 main3d_LDADD = $(IBAMR_LDFLAGS) $(IBAMR3d_LIBS) $(IBAMR_LIBS)
 main3d_SOURCES = main.cpp
+failed_sheet2d_generator_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=2
+failed_sheet2d_generator_LDADD = $(IBAMR_LDFLAGS) $(IBAMR2d_LIBS) $(IBAMR_LIBS)
+failed_sheet2d_generator_SOURCES = generate_failed_sheet2d.cpp
 failed_sheet3d_generator_CXXFLAGS = $(AM_CXXFLAGS) -DNDIM=3
 failed_sheet3d_generator_LDADD = $(IBAMR_LDFLAGS) $(IBAMR3d_LIBS) $(IBAMR_LIBS)
 failed_sheet3d_generator_SOURCES = generate_failed_sheet3d.cpp
@@ -512,9 +540,17 @@ $(ACLOCAL_M4): @MAINTAINER_MODE_TRUE@ $(am__aclocal_m4_deps)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
 $(am__aclocal_m4_deps):
 
+failed_sheet2d_generator$(EXEEXT): $(failed_sheet2d_generator_OBJECTS) $(failed_sheet2d_generator_DEPENDENCIES) $(EXTRA_failed_sheet2d_generator_DEPENDENCIES) 
+	@rm -f failed_sheet2d_generator$(EXEEXT)
+	$(AM_V_CXXLD)$(failed_sheet2d_generator_LINK) $(failed_sheet2d_generator_OBJECTS) $(failed_sheet2d_generator_LDADD) $(LIBS)
+
 failed_sheet3d_generator$(EXEEXT): $(failed_sheet3d_generator_OBJECTS) $(failed_sheet3d_generator_DEPENDENCIES) $(EXTRA_failed_sheet3d_generator_DEPENDENCIES) 
 	@rm -f failed_sheet3d_generator$(EXEEXT)
 	$(AM_V_CXXLD)$(failed_sheet3d_generator_LINK) $(failed_sheet3d_generator_OBJECTS) $(failed_sheet3d_generator_LDADD) $(LIBS)
+
+main2d$(EXEEXT): $(main2d_OBJECTS) $(main2d_DEPENDENCIES) $(EXTRA_main2d_DEPENDENCIES) 
+	@rm -f main2d$(EXEEXT)
+	$(AM_V_CXXLD)$(main2d_LINK) $(main2d_OBJECTS) $(main2d_LDADD) $(LIBS)
 
 main3d$(EXEEXT): $(main3d_OBJECTS) $(main3d_DEPENDENCIES) $(EXTRA_main3d_DEPENDENCIES) 
 	@rm -f main3d$(EXEEXT)
@@ -526,7 +562,9 @@ mostlyclean-compile:
 distclean-compile:
 	-rm -f *.tab.c
 
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Po@am__quote@ # am--include-marker
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Po@am__quote@ # am--include-marker
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/main2d-main.Po@am__quote@ # am--include-marker
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/main3d-main.Po@am__quote@ # am--include-marker
 
 $(am__depfiles_remade):
@@ -559,6 +597,20 @@ am--depfiles: $(am__depfiles_remade)
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
 @am__fastdepCXX_FALSE@	$(AM_V_CXX@am__nodep@)$(LTCXXCOMPILE) -c -o $@ $<
 
+failed_sheet2d_generator-generate_failed_sheet2d.o: generate_failed_sheet2d.cpp
+@am__fastdepCXX_TRUE@	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(failed_sheet2d_generator_CXXFLAGS) $(CXXFLAGS) -MT failed_sheet2d_generator-generate_failed_sheet2d.o -MD -MP -MF $(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Tpo -c -o failed_sheet2d_generator-generate_failed_sheet2d.o `test -f 'generate_failed_sheet2d.cpp' || echo '$(srcdir)/'`generate_failed_sheet2d.cpp
+@am__fastdepCXX_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Tpo $(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Po
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	$(AM_V_CXX)source='generate_failed_sheet2d.cpp' object='failed_sheet2d_generator-generate_failed_sheet2d.o' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCXX_FALSE@	$(AM_V_CXX@am__nodep@)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(failed_sheet2d_generator_CXXFLAGS) $(CXXFLAGS) -c -o failed_sheet2d_generator-generate_failed_sheet2d.o `test -f 'generate_failed_sheet2d.cpp' || echo '$(srcdir)/'`generate_failed_sheet2d.cpp
+
+failed_sheet2d_generator-generate_failed_sheet2d.obj: generate_failed_sheet2d.cpp
+@am__fastdepCXX_TRUE@	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(failed_sheet2d_generator_CXXFLAGS) $(CXXFLAGS) -MT failed_sheet2d_generator-generate_failed_sheet2d.obj -MD -MP -MF $(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Tpo -c -o failed_sheet2d_generator-generate_failed_sheet2d.obj `if test -f 'generate_failed_sheet2d.cpp'; then $(CYGPATH_W) 'generate_failed_sheet2d.cpp'; else $(CYGPATH_W) '$(srcdir)/generate_failed_sheet2d.cpp'; fi`
+@am__fastdepCXX_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Tpo $(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Po
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	$(AM_V_CXX)source='generate_failed_sheet2d.cpp' object='failed_sheet2d_generator-generate_failed_sheet2d.obj' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCXX_FALSE@	$(AM_V_CXX@am__nodep@)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(failed_sheet2d_generator_CXXFLAGS) $(CXXFLAGS) -c -o failed_sheet2d_generator-generate_failed_sheet2d.obj `if test -f 'generate_failed_sheet2d.cpp'; then $(CYGPATH_W) 'generate_failed_sheet2d.cpp'; else $(CYGPATH_W) '$(srcdir)/generate_failed_sheet2d.cpp'; fi`
+
 failed_sheet3d_generator-generate_failed_sheet3d.o: generate_failed_sheet3d.cpp
 @am__fastdepCXX_TRUE@	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(failed_sheet3d_generator_CXXFLAGS) $(CXXFLAGS) -MT failed_sheet3d_generator-generate_failed_sheet3d.o -MD -MP -MF $(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Tpo -c -o failed_sheet3d_generator-generate_failed_sheet3d.o `test -f 'generate_failed_sheet3d.cpp' || echo '$(srcdir)/'`generate_failed_sheet3d.cpp
 @am__fastdepCXX_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Tpo $(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Po
@@ -572,6 +624,20 @@ failed_sheet3d_generator-generate_failed_sheet3d.obj: generate_failed_sheet3d.cp
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	$(AM_V_CXX)source='generate_failed_sheet3d.cpp' object='failed_sheet3d_generator-generate_failed_sheet3d.obj' libtool=no @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
 @am__fastdepCXX_FALSE@	$(AM_V_CXX@am__nodep@)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(failed_sheet3d_generator_CXXFLAGS) $(CXXFLAGS) -c -o failed_sheet3d_generator-generate_failed_sheet3d.obj `if test -f 'generate_failed_sheet3d.cpp'; then $(CYGPATH_W) 'generate_failed_sheet3d.cpp'; else $(CYGPATH_W) '$(srcdir)/generate_failed_sheet3d.cpp'; fi`
+
+main2d-main.o: main.cpp
+@am__fastdepCXX_TRUE@	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(main2d_CXXFLAGS) $(CXXFLAGS) -MT main2d-main.o -MD -MP -MF $(DEPDIR)/main2d-main.Tpo -c -o main2d-main.o `test -f 'main.cpp' || echo '$(srcdir)/'`main.cpp
+@am__fastdepCXX_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/main2d-main.Tpo $(DEPDIR)/main2d-main.Po
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	$(AM_V_CXX)source='main.cpp' object='main2d-main.o' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCXX_FALSE@	$(AM_V_CXX@am__nodep@)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(main2d_CXXFLAGS) $(CXXFLAGS) -c -o main2d-main.o `test -f 'main.cpp' || echo '$(srcdir)/'`main.cpp
+
+main2d-main.obj: main.cpp
+@am__fastdepCXX_TRUE@	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(main2d_CXXFLAGS) $(CXXFLAGS) -MT main2d-main.obj -MD -MP -MF $(DEPDIR)/main2d-main.Tpo -c -o main2d-main.obj `if test -f 'main.cpp'; then $(CYGPATH_W) 'main.cpp'; else $(CYGPATH_W) '$(srcdir)/main.cpp'; fi`
+@am__fastdepCXX_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/main2d-main.Tpo $(DEPDIR)/main2d-main.Po
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	$(AM_V_CXX)source='main.cpp' object='main2d-main.obj' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCXX_FALSE@	$(AM_V_CXX@am__nodep@)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(main2d_CXXFLAGS) $(CXXFLAGS) -c -o main2d-main.obj `if test -f 'main.cpp'; then $(CYGPATH_W) 'main.cpp'; else $(CYGPATH_W) '$(srcdir)/main.cpp'; fi`
 
 main3d-main.o: main.cpp
 @am__fastdepCXX_TRUE@	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(main3d_CXXFLAGS) $(CXXFLAGS) -MT main3d-main.o -MD -MP -MF $(DEPDIR)/main3d-main.Tpo -c -o main3d-main.o `test -f 'main.cpp' || echo '$(srcdir)/'`main.cpp
@@ -718,7 +784,9 @@ clean: clean-am
 clean-am: clean-generic clean-libtool clean-local mostlyclean-am
 
 distclean: distclean-am
-		-rm -f ./$(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Po
+		-rm -f ./$(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Po
+	-rm -f ./$(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Po
+	-rm -f ./$(DEPDIR)/main2d-main.Po
 	-rm -f ./$(DEPDIR)/main3d-main.Po
 	-rm -f Makefile
 distclean-am: clean-am distclean-compile distclean-generic \
@@ -765,7 +833,9 @@ install-ps-am:
 installcheck-am:
 
 maintainer-clean: maintainer-clean-am
-		-rm -f ./$(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Po
+		-rm -f ./$(DEPDIR)/failed_sheet2d_generator-generate_failed_sheet2d.Po
+	-rm -f ./$(DEPDIR)/failed_sheet3d_generator-generate_failed_sheet3d.Po
+	-rm -f ./$(DEPDIR)/main2d-main.Po
 	-rm -f ./$(DEPDIR)/main3d-main.Po
 	-rm -f Makefile
 maintainer-clean-am: distclean-am maintainer-clean-generic
@@ -809,6 +879,8 @@ uninstall-am:
 
 examples: $(EXTRA_PROGRAMS)
 	if test "$(top_srcdir)" != "$(top_builddir)" ; then \
+	  cp -f $(srcdir)/input2d.failure $(PWD) ; \
+	  cp -f $(srcdir)/generate_failed_sheet2d.cpp $(PWD) ; \
 	  cp -f $(srcdir)/input3d.failure $(PWD) ; \
 	  cp -f $(srcdir)/generate_failed_sheet3d.cpp $(PWD) ; \
 	fi ;
@@ -816,6 +888,8 @@ examples: $(EXTRA_PROGRAMS)
 clean-local:
 	rm -f $(EXTRA_PROGRAMS)
 	if test "$(top_srcdir)" != "$(top_builddir)" ; then \
+	  rm -f $(builddir)/input2d.failure ; \
+	  rm -f $(builddir)/generate_failed_sheet2d.cpp ; \
 	  rm -f $(builddir)/input3d.failure ; \
 	  rm -f $(builddir)/generate_failed_sheet3d.cpp ; \
 	fi ;
